
#undef __ILDA_TYPE__
#undef INT_NAME


#undef CONCAT2
#undef CONCAT3

#undef CONCAT_NO_SPACEx
#undef CONCAT_NO_SPACE

#undef INT_SUFFIX
#undef FLOAT_SUFFIX
#undef DOUBLE_SUFFIX

#undef ILDA_TYPE
#undef ILDA_BASE_TYPE
#undef ILDA_DEC_BASE_TYPE
#undef ILDA_DEC_TYPE

#undef ILDA_FUNCTION
#undef ILDA_SIMPLE_FUNCTION